// source: colors_and_type.css · sha256 4ba767b087ffc0e4e2ec1073f2bbe2d6dc80997a864ed6172ed8ee24be710de1 · 88 tokens · built 2026-08-02T08:26:35Z 
// GENERATED by tools/build-tokens.js — DO NOT EDIT BY HAND.
// Vendored copy is stale if __source.sha256 differs from the canon
// (`node tools/build-tokens.js --sha` in the design-system repo).
export const __source = { file: "colors_and_type.css", sha256: "4ba767b087ffc0e4e2ec1073f2bbe2d6dc80997a864ed6172ed8ee24be710de1", tokens: 88, built: "2026-08-02T08:26:35Z" };

export const theme = {
  cherry: "#A4161A", // primary brand accent — CTAs, marks, active nav ONLY
  cherryHover: "#8B1218", // CTA :hover
  cherryDark: "#7A1014", // pressed / deep
  cherryTint: "#FDF2F2", // faint cherry surface (oauth hover, anchors)
  cherrySoft: "#F2E0E0", // avatar / chip wash
  cherryMuted: "#D4888A", // dividers, de-emphasised marks
  fg1: "#111318", // primary text
  fg2: "#636B7D", // secondary text, labels
  fg3: "#9CA3AF", // tertiary / placeholder / mono meta
  bg: "#F6F7F9", // default page background
  surface: "#FFFFFF", // cards, sheets, inputs
  surfaceSunk: "#EEF0F4", // segmented-control track, search field, chips
  border: "#EEF0F4", // hairline borders (cool)
  borderStrong: "#E2E5EB", // cool divider inside cards (one step darker than --border)
  borderHeavy: "#D7DAE0", // one step darker again — sheet grabbers, placeholder fills
  surfaceTrack: "#E6E9EF", // segmented-control track ONLY — darker than --surface-sunk so the white active pill reads
  slateBg: "#F1F5F9", // neutral non-status action / «Прочее»
  slateFg: "#475569", // neutral non-status action / «Прочее»
  surfaceInverse: "#161A1D",
  onDarkFg: "#FFFFFF",
  onDarkFg2: "#9CA3AF",
  onDarkLink: "#FFD9DA", // the ONLY cherry-family colour legible on --surface-inverse
  successBg: "#F0FDF4",
  successFg: "#15803D",
  successBd: "#BBF7D0",
  warningBg: "#FFFBEB",
  warningFg: "#B45309",
  warningBd: "#FDE68A",
  infoBg: "#EFF6FF",
  infoFg: "#1D4ED8",
  infoBd: "#BFDBFE",
  plannedBg: "#F5F3FF",
  plannedFg: "#6D28D9",
  plannedBd: "#DDD6FE",
  errorBg: "#FEF2F2",
  errorFg: "#B91C1C",
  errorBd: "#FECACA",
  catFoodBg: "#FFFBEB", // Питание
  catFoodFg: "#B45309", // Питание
  catFuelBg: "#EFF6FF", // Топливо
  catFuelFg: "#1D4ED8", // Топливо
  catMaterialsBg: "#ECFDF5", // Материалы
  catMaterialsFg: "#047857", // Материалы
  catHospitalityBg: "#FDF2F2", // Представительские — the one cherry category
  catHospitalityFg: "#A4161A", // Представительские — the one cherry category
  catOtherBg: "#F1F5F9", // Прочее / не учит. в НУ
  catOtherFg: "#475569", // Прочее / не учит. в НУ
  catTravelBg: "#ECFEFF",
  catTravelFg: "#0E7490",
  catOfficeBg: "#F7FEE7",
  catOfficeFg: "#4D7C0F",
  catCommsBg: "#EEF2FF",
  catCommsFg: "#4338CA",
  catItBg: "#F5F3FF",
  catItFg: "#6D28D9",
  catMarketingBg: "#FDF4FF",
  catMarketingFg: "#A21CAF",
  catServicesBg: "#FFF7ED",
  catServicesFg: "#C2410C",
  chart1: "#A4161A",
  chart2: "#1D4ED8",
  chart3: "#047857",
  chart4: "#B45309",
  chart5: "#0E7490",
  chart6: "#475569",
  cherryRamp1: "#A4161A",
  cherryRamp2: "#C45558",
  cherryRamp3: "#D4888A",
  cherryRamp4: "#E8A0A2",
  fontSans: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  fontMono: "'Courier New', Courier, ui-monospace, monospace", // receipt / fiscal data only
  rButton: "8px", // buttons, inputs
  rCard: "12px", // cards, sheets, modals
  rPill: "999px", // badges, chips, avatars
  rSm: "6px", // small inner controls
  shadowCard: "0 1px 3px rgba(17, 19, 24, 0.04)", // resting card
  shadowModal: "0 8px 30px rgba(17, 19, 24, 0.25)", // modals only — cool base #111318
  scrim: "rgba(22, 26, 29, 0.45)", // sheet/modal overlay
  s1: "4px",
  s2: "8px",
  s3: "12px",
  s4: "16px",
  s5: "20px",
  s6: "24px",
  s8: "32px",
  s10: "40px",
  tap: "opacity 120ms ease", // @kind other
  ui: "background 120ms ease, border-color 120ms ease", // @kind other
};

export const colors = {
  cherry: "#A4161A",
  cherryHover: "#8B1218",
  cherryDark: "#7A1014",
  cherryTint: "#FDF2F2",
  cherrySoft: "#F2E0E0",
  cherryMuted: "#D4888A",
  fg1: "#111318",
  fg2: "#636B7D",
  fg3: "#9CA3AF",
  bg: "#F6F7F9",
  surface: "#FFFFFF",
  surfaceSunk: "#EEF0F4",
  border: "#EEF0F4",
  borderStrong: "#E2E5EB",
  borderHeavy: "#D7DAE0",
  surfaceTrack: "#E6E9EF",
  slateBg: "#F1F5F9",
  slateFg: "#475569",
  surfaceInverse: "#161A1D",
  onDarkFg: "#FFFFFF",
  onDarkFg2: "#9CA3AF",
  onDarkLink: "#FFD9DA",
  successBg: "#F0FDF4",
  successFg: "#15803D",
  successBd: "#BBF7D0",
  warningBg: "#FFFBEB",
  warningFg: "#B45309",
  warningBd: "#FDE68A",
  infoBg: "#EFF6FF",
  infoFg: "#1D4ED8",
  infoBd: "#BFDBFE",
  plannedBg: "#F5F3FF",
  plannedFg: "#6D28D9",
  plannedBd: "#DDD6FE",
  errorBg: "#FEF2F2",
  errorFg: "#B91C1C",
  errorBd: "#FECACA",
  catFoodBg: "#FFFBEB",
  catFoodFg: "#B45309",
  catFuelBg: "#EFF6FF",
  catFuelFg: "#1D4ED8",
  catMaterialsBg: "#ECFDF5",
  catMaterialsFg: "#047857",
  catHospitalityBg: "#FDF2F2",
  catHospitalityFg: "#A4161A",
  catOtherBg: "#F1F5F9",
  catOtherFg: "#475569",
  catTravelBg: "#ECFEFF",
  catTravelFg: "#0E7490",
  catOfficeBg: "#F7FEE7",
  catOfficeFg: "#4D7C0F",
  catCommsBg: "#EEF2FF",
  catCommsFg: "#4338CA",
  catItBg: "#F5F3FF",
  catItFg: "#6D28D9",
  catMarketingBg: "#FDF4FF",
  catMarketingFg: "#A21CAF",
  catServicesBg: "#FFF7ED",
  catServicesFg: "#C2410C",
  chart1: "#A4161A",
  chart2: "#1D4ED8",
  chart3: "#047857",
  chart4: "#B45309",
  chart5: "#0E7490",
  chart6: "#475569",
  cherryRamp1: "#A4161A",
  cherryRamp2: "#C45558",
  cherryRamp3: "#D4888A",
  cherryRamp4: "#E8A0A2",
  scrim: "rgba(22, 26, 29, 0.45)",
};

// cssVar('cherryHover') -> 'var(--cherry-hover)'
export const cssVar = (k) => 'var(--' + k.replace(/[A-Z0-9]/g, (c) => '-' + c.toLowerCase()) + ')';
